# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  CCACHE_DIR: $(Pipeline.Workspace)/ccache

steps:
- task: Bash@3
  displayName: 'Set up Buildroot'
  inputs:
    filePath: 'setup-build.sh'

- task: Cache@2
  inputs:
    key: 'ccache | "$(Agent.OS)"'
    path: $(CCACHE_DIR)
  displayName: Setup Buildroot ccache

- task: Bash@3
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: |
      export SYSTEM=`uname -s`
      export BR2_CCACHE_DIR=$CCACHE_DIR
      env
      cd build
      make

- task: GitHubRelease@1
  displayName: 'Publish artifact'
  inputs:
    gitHubConnection: 'github.com_frbncis'
    repositoryName: 'frbncis/barrier-dongle'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    assets: '$(Build.SourcesDirectory)/build/images/*.img'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    tagPattern: '*'
    tag: '$(Build.BuildNumber)'