# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Setup buildroot
  inputs:
    filePath: 'setup-build.sh'

- task: Build
  inputs:
    targetType: 'inline'
    script: |
      cd build
      make