# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: Bash@3
#   inputs:
#     filePath: 'setup-build.sh'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       cd build
#       make

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_frbncis'
    repositoryName: 'frbncis/barrier-dongle'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    assets: '$(Build.SourcesDirectory)/build/images/*.img'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    tagPattern: '*'
    tag: '$(tagName)'