#!/bin/sh
#
## barrierc daemon init script

DAEMON=/usr/bin/barrierc
source /data/barrierc.txt

case "$1" in
    start)
        GADGET=/sys/kernel/config/usb_gadget/barrierc
        SERIAL=`cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2`

        mount -t configfs none /sys/kernel/config
        mkdir -p $GADGET

        (cd $GADGET
          echo 0x1d6b > idVendor # Linux Foundation
          echo 0x0104 > idProduct # Multifunction Composite Gadget
          echo 0x0100 > bcdDevice # v1.0.0
          echo 0x0200 > bcdUSB # USB2

          mkdir strings/0x409
          echo $SERIAL > strings/0x409/serialnumber
          echo "Raspberry Pi" > strings/0x409/manufacturer
          echo "Pi Zero W" > strings/0x409/product

          mkdir -p configs/c.1/strings/0x409
          echo "Config 1" > configs/c.1/strings/0x409/configuration
          echo 500 > configs/c.1/MaxPower

          # Keyboard
          mkdir -p functions/hid.usb0
          echo 1 > functions/hid.usb0/protocol
          echo 1 > functions/hid.usb0/subclass
          echo 8 > functions/hid.usb0/report_length
          echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc
          ln -s functions/hid.usb0 configs/c.1/

          # Mouse
          mkdir -p functions/hid.usb1
          echo 2 > functions/hid.usb1/protocol
          echo 1 > functions/hid.usb1/subclass
          echo 4 > functions/hid.usb1/report_length
          echo -ne \\x05\\x01\\x09\\x02\\xA1\\x01\\x05\\x09\\x19\\x01\\x29\\x08\\x15\\x00\\x25\\x01\\x95\\x08\\x75\\x01\\x81\\x02\\x05\\x01\\x09\\x38\\x15\\x81\\x25\\x7F\\x75\\x08\\x95\\x01\\x81\\x06\\x09\\x30\\x09\\x31\\x16\\x00\\x80\\x26\\xFF\\x7F\\x75\\x10\\x95\\x02\\x81\\x06\\xC0 > functions/hid.usb1/report_desc
          ln -s functions/hid.usb1 configs/c.1/

          ls /sys/class/udc > UDC
        )

        $DAEMON $BARRIERC_ARGS
        ;;
    stop)
        killall -9 barrierc
        ;;
    reload)
        killall -9 barrierc
        $DAEMON $BARRIERC_ARGS
        ;;
    *)
        echo "Usage: S99barrierc-daemon {start|stop|reload}" >&2
        exit 1
        ;;
esac

